In [16]:
import pandas as pd 
import requests 
import time 
from bs4 import BeautifulSoup

headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1"
}

In [26]:
df = pd.read_csv("shooting.csv",sep = "\t")

In [27]:
df.head()

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
0,1,Myenty Abena,sr SUR,DF,Gaziantep FK,31-149,1994,20.4,1,9,2,22.2,0.44,0.10,0.11,0.50,0,0,Matches
1,2,Tammy Abraham,eng ENG,FW,Beşiktaş,28-220,1997,13.9,7,32,16,50.0,2.31,1.15,0.19,0.38,1,2,Matches
2,3,Yaw Ackah,gh GHA,MF,Kayserispor,26-343,1999,2.0,0,2,1,50.0,0.98,0.49,0.00,0.00,0,0,Matches
3,4,Emmanuel Agbadou,ci CIV,DF,Beşiktaş,28-327,1997,11.1,1,9,4,44.4,0.81,0.36,0.11,0.25,0,0,Matches
4,5,Dan Agyei,gh GHA,"MF,FW",Kocaelispor,28-343,1997,22.8,5,46,17,37.0,2.02,0.75,0.11,0.29,0,0,Matches

In [32]:
misc = pd.read_csv("misc.csv", sep="\t", encoding="utf-8-sig")
print(misc.shape)
misc.head()

(609, 1)

                                     \tPerformance\t
0  Rk\tPlayer\tNation\tPos\tSquad\tAge\tBorn\t90s...
1  1\tMyenty Abena\tsr SUR\tDF\tGaziantep FK\t31-...
2  2\tTammy Abraham\teng ENG\tFW\tBe≈üikta≈ü\t28-...
3  3\tYaw Ackah\tgh GHA\tMF\tKayserispor\t26-345\...
4  4\tEmmanuel Agbadou\tci CIV\tDF\tBe≈üikta≈ü\t2...

In [33]:
import os
print(os.listdir())

['.DS_Store', 'requirements.txt', 'misc.csv', '.gitignore', 'shooting.csv', '.ipynb_checkpoints', 'transfermarkt.csv', 'venv', '.git', 'standard.csv', 'transfer-deger-tahmini.ipynb']

In [34]:
with open("misc.csv", "r", encoding="utf-8") as f:
    print(f.read()[:500])

﻿"	Performance	"
"Rk	Player	Nation	Pos	Squad	Age	Born	90s	CrdY	CrdR	2CrdY	Fls	Fld	Off	Crs	Int	TklW	PKwon	PKcon	OG	Matches"
"1	Myenty Abena	sr SUR	DF	Gaziantep FK	31-151	1994	20.4	2	1	0	22	17	1	1	14	21			1	Matches"
"2	Tammy Abraham	eng ENG	FW	Be≈üikta≈ü	28-222	1997	13.9	3	0	0	25	12	9	4	6	2			0	Matches"
"3	Yaw Ackah	gh GHA	MF	Kayserispor	26-345	1999	2.0	0	0	0	2	2	0	0	1	0			0	Matches"
"4	Emmanuel Agbadou	ci CIV	DF	Be≈üikta≈ü	28-329	1997	11.1	3	0	0	16	5	1	3	13	15			0	Matches"
"5	Dan Agyei	gh GHA	MF,

In [35]:
misc = pd.read_csv("misc.csv", sep="\t", encoding="utf-8")
print("Sütun sayısı:", misc.shape[1])
print("Sütunlar:", misc.columns.tolist())

Sütun sayısı: 1
Sütunlar: ['\tPerformance\t']

In [36]:
misc = pd.read_csv("misc.csv", sep="\t", encoding="utf-8")
print(misc.shape)
misc.head()

(609, 3)

,,,,,,,,,,,,,,,,,,Unnamed: 0,Performance,Unnamed: 2
Rk,Player,Nation,Pos,Squad,Age,Born,90s,CrdY,CrdR,2CrdY,Fls,Fld,Off,Crs,Int,TklW,PKwon,PKcon,OG,Matches
1,Myenty Abena,sr SUR,DF,Gaziantep FK,31-151,1994,20.4,2,1,0,22,17,1,1,14,21,NaN,NaN,1,Matches
2,Tammy Abraham,eng ENG,FW,Beşiktaş,28-222,1997,13.9,3,0,0,25,12,9,4,6,2,NaN,NaN,0,Matches
3,Yaw Ackah,gh GHA,MF,Kayserispor,26-345,1999,2.0,0,0,0,2,2,0,0,1,0,NaN,NaN,0,Matches
4,Emmanuel Agbadou,ci CIV,DF,Beşiktaş,28-329,1997,11.1,3,0,0,16,5,1,3,13,15,NaN,NaN,0,Matches

In [ ]:
play = pd.read_csv("playing.csv", sep="\t", encoding="utf-8")
print(play.shape)
play.head()